const UPDATE_DIMENSIONS = "UPDATE_DIMENSIONS";
const UPDATE_ROUND = "UPDATE_ROUND";
const END_GAME = "END_GAME";
const UPDATE_TURN = "UPDATE_TURN";
const RESET_ROUND = "RESET_ROUND";

export { UPDATE_DIMENSIONS, UPDATE_ROUND, UPDATE_TURN, END_GAME, RESET_ROUND };
